export interface Product {
  id: number;
  name: string;
  price_per_quantity: number;
  type: string;
  status: string;
  color: string;
}

export const products = [
  {
    id: 1,
    name: 'Classic Cotton T-Shirt',
    price_per_quantity: 25.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 2,
    name: 'Denim Jeans',
    price_per_quantity: 89.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 3,
    name: 'Running Sneakers',
    price_per_quantity: 129.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 4,
    name: 'Aviator Sunglasses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 5,
    name: 'Digital Sports Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 6,
    name: 'Baseball Cap',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 7,
    name: 'Leather Jacket',
    price_per_quantity: 399.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 8,
    name: 'Polo Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 9,
    name: 'Chino Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 10,
    name: 'Canvas High-tops',
    price_per_quantity: 79.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 11,
    name: 'Wayframe Sunglasses',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 12,
    name: 'Chronograph Watch',
    price_per_quantity: 599.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 13,
    name: 'Beanie Hat',
    price_per_quantity: 19.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 14,
    name: 'Bomber Jacket',
    price_per_quantity: 179.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 15,
    name: 'Button-down Shirt',
    price_per_quantity: 59.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 16,
    name: 'Cargo Pants',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 17,
    name: 'Dress Shoes',
    price_per_quantity: 199.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 18,
    name: 'Round Sunglasses',
    price_per_quantity: 129.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 19,
    name: 'Minimalist Watch',
    price_per_quantity: 249.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 20,
    name: 'Fedora Hat',
    price_per_quantity: 89.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 21,
    name: 'Denim Jacket',
    price_per_quantity: 119.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 22,
    name: 'Flannel Shirt',
    price_per_quantity: 45.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 23,
    name: 'Jogger Pants',
    price_per_quantity: 54.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 24,
    name: 'Basketball Shoes',
    price_per_quantity: 159.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 25,
    name: 'Cat-eye Sunglasses',
    price_per_quantity: 169.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 26,
    name: 'Luxury Watch',
    price_per_quantity: 1299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 27,
    name: 'Bucket Hat',
    price_per_quantity: 29.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 28,
    name: 'Windbreaker Jacket',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 29,
    name: 'Henley Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 30,
    name: 'Skinny Jeans',
    price_per_quantity: 94.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 31,
    name: 'Hiking Boots',
    price_per_quantity: 189.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 32,
    name: 'Sports Sunglasses',
    price_per_quantity: 119.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 33,
    name: 'Smartwatch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 34,
    name: 'Trucker Hat',
    price_per_quantity: 24.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 35,
    name: 'Puffer Jacket',
    price_per_quantity: 249.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 36,
    name: 'V-neck T-shirt',
    price_per_quantity: 22.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 37,
    name: 'Sweatpants',
    price_per_quantity: 49.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 38,
    name: 'Loafers',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 39,
    name: 'Oversized Sunglasses',
    price_per_quantity: 189.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 40,
    name: 'Dive Watch',
    price_per_quantity: 699.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 41,
    name: 'Snapback Cap',
    price_per_quantity: 32.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 42,
    name: 'Trench Coat',
    price_per_quantity: 299.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 43,
    name: 'Dress Shirt',
    price_per_quantity: 79.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 44,
    name: 'Track Pants',
    price_per_quantity: 59.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 45,
    name: 'Sandals',
    price_per_quantity: 69.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 46,
    name: 'Pilot Sunglasses',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 47,
    name: 'Field Watch',
    price_per_quantity: 199.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 48,
    name: 'Beret',
    price_per_quantity: 39.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 49,
    name: 'Peacoat',
    price_per_quantity: 219.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 50,
    name: 'Tank Top',
    price_per_quantity: 19.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 51,
    name: 'Shorts',
    price_per_quantity: 39.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 52,
    name: 'Flip Flops',
    price_per_quantity: 24.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 53,
    name: 'Square Sunglasses',
    price_per_quantity: 139.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 54,
    name: 'Racing Watch',
    price_per_quantity: 799.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 55,
    name: 'Visor Hat',
    price_per_quantity: 21.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 56,
    name: 'Varsity Jacket',
    price_per_quantity: 159.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 57,
    name: 'Graphic T-shirt',
    price_per_quantity: 29.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 58,
    name: 'Leggings',
    price_per_quantity: 44.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 59,
    name: 'Combat Boots',
    price_per_quantity: 169.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 60,
    name: 'Mirrored Sunglasses',
    price_per_quantity: 159.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 61,
    name: 'Vintage Watch',
    price_per_quantity: 449.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 62,
    name: 'Sun Hat',
    price_per_quantity: 49.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 63,
    name: 'Rain Jacket',
    price_per_quantity: 99.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 64,
    name: 'Long Sleeve Shirt',
    price_per_quantity: 34.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 65,
    name: 'Dress Pants',
    price_per_quantity: 99.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 66,
    name: 'Oxford Shoes',
    price_per_quantity: 179.99,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 67,
    name: 'Fashion Sunglasses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 68,
    name: 'Automatic Watch',
    price_per_quantity: 999.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 69,
    name: 'Winter Hat',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 70,
    name: 'Fleece Jacket',
    price_per_quantity: 79.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 71,
    name: 'Striped Shirt',
    price_per_quantity: 42.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 72,
    name: 'Khaki Pants',
    price_per_quantity: 64.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 73,
    name: 'Boat Shoes',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 74,
    name: 'Retro Sunglasses',
    price_per_quantity: 89.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 75,
    name: 'Skeleton Watch',
    price_per_quantity: 349.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 76,
    name: 'Cowboy Hat',
    price_per_quantity: 129.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 77,
    name: 'Blazer',
    price_per_quantity: 199.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 78,
    name: 'Muscle Shirt',
    price_per_quantity: 24.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 79,
    name: 'Yoga Pants',
    price_per_quantity: 54.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 80,
    name: 'High-top Sneakers',
    price_per_quantity: 99.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 81,
    name: 'Gradient Sunglasses',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 82,
    name: 'GMT Watch',
    price_per_quantity: 549.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 83,
    name: 'Newsboy Cap',
    price_per_quantity: 44.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 84,
    name: 'Parka',
    price_per_quantity: 279.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 85,
    name: 'Plaid Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 86,
    name: 'Wide-leg Pants',
    price_per_quantity: 74.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 87,
    name: 'Espadrilles',
    price_per_quantity: 59.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 88,
    name: 'Wraparound Sunglasses',
    price_per_quantity: 109.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 89,
    name: 'Pilot Watch',
    price_per_quantity: 699.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 90,
    name: 'Fishing Hat',
    price_per_quantity: 39.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 91,
    name: 'Harrington Jacket',
    price_per_quantity: 149.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 92,
    name: 'Turtleneck',
    price_per_quantity: 59.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 93,
    name: 'Palazzo Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 94,
    name: 'Clogs',
    price_per_quantity: 89.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 95,
    name: 'Shield Sunglasses',
    price_per_quantity: 189.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 96,
    name: 'Moonphase Watch',
    price_per_quantity: 1199.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 97,
    name: 'Cloche Hat',
    price_per_quantity: 54.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 98,
    name: 'Military Jacket',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 99,
    name: 'Chambray Shirt',
    price_per_quantity: 52.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 100,
    name: 'Cropped Pants',
    price_per_quantity: 59.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 101,
    name: 'Moccasins',
    price_per_quantity: 79.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 102,
    name: 'Clubmaster Sunglasses',
    price_per_quantity: 169.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 103,
    name: 'Dress Watch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 104,
    name: 'Panama Hat',
    price_per_quantity: 89.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 105,
    name: 'Cardigan',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 106,
    name: 'Work Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 107,
    name: 'Capri Pants',
    price_per_quantity: 49.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 108,
    name: 'Slip-on Shoes',
    price_per_quantity: 69.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 109,
    name: 'Hexagonal Sunglasses',
    price_per_quantity: 129.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 110,
    name: 'Quartz Watch',
    price_per_quantity: 149.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 111,
    name: 'Boater Hat',
    price_per_quantity: 64.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 112,
    name: 'Double-breasted Coat',
    price_per_quantity: 349.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 113,
    name: 'Safari Shirt',
    price_per_quantity: 69.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 114,
    name: 'Harem Pants',
    price_per_quantity: 44.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 115,
    name: 'Platform Shoes',
    price_per_quantity: 109.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 116,
    name: 'Geometric Sunglasses',
    price_per_quantity: 159.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 117,
    name: 'Tourbillon Watch',
    price_per_quantity: 2999.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 118,
    name: 'Top Hat',
    price_per_quantity: 199.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 119,
    name: 'Motorcycle Jacket',
    price_per_quantity: 459.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 120,
    name: 'Baseball Jersey',
    price_per_quantity: 79.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 121,
    name: 'Bell-bottom Pants',
    price_per_quantity: 84.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 122,
    name: 'Mary Jane Shoes',
    price_per_quantity: 89.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 123,
    name: 'Tinted Sunglasses',
    price_per_quantity: 99.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 124,
    name: 'Pocket Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 125,
    name: 'Sombrero',
    price_per_quantity: 79.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Yellow',
  },
  {
    id: 126,
    name: 'Duster Coat',
    price_per_quantity: 229.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 127,
    name: 'Rugby Shirt',
    price_per_quantity: 59.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 128,
    name: 'Parachute Pants',
    price_per_quantity: 64.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 129,
    name: 'Wellington Boots',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 130,
    name: 'Butterfly Sunglasses',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 131,
    name: 'Perpetual Calendar Watch',
    price_per_quantity: 4999.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 132,
    name: 'Bowler Hat',
    price_per_quantity: 89.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 133,
    name: 'Cape',
    price_per_quantity: 149.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 134,
    name: 'Mesh Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 135,
    name: 'Cargo Shorts',
    price_per_quantity: 44.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 136,
    name: 'Gladiator Sandals',
    price_per_quantity: 79.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 137,
    name: 'Heart-shaped Sunglasses',
    price_per_quantity: 69.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 138,
    name: 'Solar Watch',
    price_per_quantity: 259.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 139,
    name: 'Pork Pie Hat',
    price_per_quantity: 74.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 140,
    name: 'Kimono Jacket',
    price_per_quantity: 129.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 141,
    name: 'Camisole',
    price_per_quantity: 29.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 142,
    name: 'Straight-leg Jeans',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 143,
    name: 'Ankle Boots',
    price_per_quantity: 139.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 144,
    name: 'Rimless Sunglasses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 145,
    name: 'Kinetic Watch',
    price_per_quantity: 329.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 146,
    name: 'Fascinator',
    price_per_quantity: 59.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 147,
    name: 'Smoking Jacket',
    price_per_quantity: 299.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 148,
    name: 'Crop Top',
    price_per_quantity: 24.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 149,
    name: 'High-waisted Pants',
    price_per_quantity: 74.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 150,
    name: 'Thigh-high Boots',
    price_per_quantity: 199.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 151,
    name: 'Steampunk Goggles',
    price_per_quantity: 89.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 152,
    name: 'Atomic Watch',
    price_per_quantity: 799.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 153,
    name: 'Deerstalker Hat',
    price_per_quantity: 69.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 154,
    name: 'Tailcoat',
    price_per_quantity: 399.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 155,
    name: 'Thermal Shirt',
    price_per_quantity: 34.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 156,
    name: 'Bootcut Jeans',
    price_per_quantity: 89.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 157,
    name: 'Chelsea Boots',
    price_per_quantity: 169.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 158,
    name: 'Clip-on Sunglasses',
    price_per_quantity: 49.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 159,
    name: 'Tactical Watch',
    price_per_quantity: 249.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 160,
    name: 'Turban',
    price_per_quantity: 39.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 161,
    name: 'Nehru Jacket',
    price_per_quantity: 179.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 162,
    name: 'Peasant Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 163,
    name: 'Palazzo Shorts',
    price_per_quantity: 39.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Yellow',
  },
  {
    id: 164,
    name: 'Wedge Shoes',
    price_per_quantity: 99.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 165,
    name: 'Photochromic Sunglasses',
    price_per_quantity: 249.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 166,
    name: 'Hybrid Watch',
    price_per_quantity: 199.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 167,
    name: 'Fez Hat',
    price_per_quantity: 49.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 168,
    name: 'Bolero Jacket',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 169,
    name: 'Raglan Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 170,
    name: 'Culottes',
    price_per_quantity: 64.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 171,
    name: 'Stiletto Heels',
    price_per_quantity: 129.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 172,
    name: '3D Glasses',
    price_per_quantity: 19.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 173,
    name: 'Fitness Watch',
    price_per_quantity: 179.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 174,
    name: 'Brimmed Hat',
    price_per_quantity: 54.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 175,
    name: 'Safari Jacket',
    price_per_quantity: 149.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 176,
    name: 'Athletic Shirt',
    price_per_quantity: 34.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Green',
  },
  {
    id: 177,
    name: 'Palazzo Trousers',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 178,
    name: 'Duck Boots',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 179,
    name: 'Vintage Sunglasses',
    price_per_quantity: 139.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 180,
    name: 'Titanium Watch',
    price_per_quantity: 599.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 181,
    name: 'Ivy Cap',
    price_per_quantity: 44.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 182,
    name: 'Shearling Jacket',
    price_per_quantity: 399.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 183,
    name: 'Compression Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 184,
    name: 'Wide-leg Jeans',
    price_per_quantity: 94.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 185,
    name: 'Penny Loafers',
    price_per_quantity: 159.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 186,
    name: 'Polarized Sunglasses',
    price_per_quantity: 189.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 187,
    name: 'Chronometer Watch',
    price_per_quantity: 899.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 188,
    name: 'Chef Hat',
    price_per_quantity: 29.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 189,
    name: 'Lab Coat',
    price_per_quantity: 79.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 190,
    name: 'Mock Turtleneck',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 191,
    name: 'Paper Bag Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 192,
    name: 'Pointed Toe Shoes',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 193,
    name: 'Safety Glasses',
    price_per_quantity: 39.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 194,
    name: 'Mechanical Watch',
    price_per_quantity: 749.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Yellow',
  },
  {
    id: 195,
    name: 'Flat Cap',
    price_per_quantity: 59.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 196,
    name: 'Utility Jacket',
    price_per_quantity: 129.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 197,
    name: 'Scoop Neck Shirt',
    price_per_quantity: 29.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 198,
    name: 'Flare Pants',
    price_per_quantity: 74.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 199,
    name: 'Riding Boots',
    price_per_quantity: 249.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 200,
    name: 'Computer Glasses',
    price_per_quantity: 79.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 201,
    name: 'GPS Watch',
    price_per_quantity: 349.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 202,
    name: 'Garrison Cap',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 203,
    name: 'Down Jacket',
    price_per_quantity: 199.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Red',
  },
  {
    id: 204,
    name: 'Batwing Shirt',
    price_per_quantity: 54.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 205,
    name: 'Stirrup Pants',
    price_per_quantity: 59.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 206,
    name: 'Monk Strap Shoes',
    price_per_quantity: 189.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 207,
    name: 'Blue Light Glasses',
    price_per_quantity: 59.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 208,
    name: 'Altimeter Watch',
    price_per_quantity: 449.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 209,
    name: 'Cadet Cap',
    price_per_quantity: 39.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 210,
    name: 'Softshell Jacket',
    price_per_quantity: 119.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 211,
    name: 'Cowl Neck Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 212,
    name: 'Cigarette Pants',
    price_per_quantity: 84.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 213,
    name: 'Brogue Shoes',
    price_per_quantity: 199.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 214,
    name: 'Reading Glasses',
    price_per_quantity: 49.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 215,
    name: 'Compass Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 216,
    name: 'Military Beret',
    price_per_quantity: 44.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 217,
    name: 'Vest',
    price_per_quantity: 69.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 218,
    name: 'Asymmetric Shirt',
    price_per_quantity: 64.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 219,
    name: 'Tapered Pants',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 220,
    name: 'Desert Boots',
    price_per_quantity: 129.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 221,
    name: 'Transition Lenses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 222,
    name: 'Rugged Watch',
    price_per_quantity: 199.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 223,
    name: 'Patrol Cap',
    price_per_quantity: 29.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 224,
    name: 'Anorak',
    price_per_quantity: 99.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 225,
    name: 'Cold Shoulder Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 226,
    name: 'Pleated Pants',
    price_per_quantity: 89.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 227,
    name: 'Wing Tip Shoes',
    price_per_quantity: 179.99,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 228,
    name: 'Driving Glasses',
    price_per_quantity: 89.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 229,
    name: 'Multisport Watch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 230,
    name: 'Slouch Hat',
    price_per_quantity: 64.99,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 231,
    name: 'Gilet',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 232,
    name: 'Wrap Shirt',
    price_per_quantity: 54.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 233,
    name: 'Sailor Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 234,
    name: 'Cap Toe Shoes',
    price_per_quantity: 169.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 235,
    name: 'Ski Goggles',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 236,
    name: 'Dive Computer Watch',
    price_per_quantity: 799.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 237,
    name: 'Boonie Hat',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 238,
    name: 'Track Jacket',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 239,
    name: 'Swing Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Yellow',
  },
  {
    id: 240,
    name: 'Palazzo Shorts',
    price_per_quantity: 49.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 241,
    name: 'Spectator Shoes',
    price_per_quantity: 199.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 242,
    name: 'Night Vision Glasses',
    price_per_quantity: 299.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 243,
    name: 'Sailing Watch',
    price_per_quantity: 649.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 244,
    name: 'Campaign Hat',
    price_per_quantity: 79.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 245,
    name: 'Windcheater',
    price_per_quantity: 79.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 246,
    name: 'Tunic Shirt',
    price_per_quantity: 59.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 247,
    name: 'Gaucho Pants',
    price_per_quantity: 74.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 248,
    name: 'Saddle Shoes',
    price_per_quantity: 139.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 249,
    name: 'Magnifying Glasses',
    price_per_quantity: 69.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 250,
    name: 'Regatta Watch',
    price_per_quantity: 549.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 251,
    name: 'Garrison Hat',
    price_per_quantity: 49.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 252,
    name: 'Oilskin Jacket',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 253,
    name: 'Empire Waist Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 254,
    name: 'Pedal Pushers',
    price_per_quantity: 54.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 255,
    name: 'T-bar Shoes',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 256,
    name: 'Magnifying Sunglasses',
    price_per_quantity: 129.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 257,
    name: 'Aviation Watch',
    price_per_quantity: 699.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 258,
    name: 'Kepi Hat',
    price_per_quantity: 54.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 259,
    name: 'Stadium Jacket',
    price_per_quantity: 149.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 260,
    name: 'Dolman Sleeve Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 261,
    name: 'Tap Pants',
    price_per_quantity: 39.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 262,
    name: 'Ballet Flats',
    price_per_quantity: 79.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 263,
    name: 'Tactical Sunglasses',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 264,
    name: 'Outdoor Watch',
    price_per_quantity: 279.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 265,
    name: 'Homburg Hat',
    price_per_quantity: 99.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 266,
    name: 'Stadium Coat',
    price_per_quantity: 199.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 267,
    name: 'Bandeau Top',
    price_per_quantity: 34.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 268,
    name: 'Hammer Pants',
    price_per_quantity: 59.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 269,
    name: 'Court Shoes',
    price_per_quantity: 109.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 270,
    name: 'Sport Sunglasses',
    price_per_quantity: 119.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 271,
    name: 'Triathlon Watch',
    price_per_quantity: 459.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 272,
    name: 'Pillbox Hat',
    price_per_quantity: 69.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Red',
  },
  {
    id: 273,
    name: 'Chore Coat',
    price_per_quantity: 119.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 274,
    name: 'Off-shoulder Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 275,
    name: 'Jodphur Pants',
    price_per_quantity: 94.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 276,
    name: 'Boat Shoes',
    price_per_quantity: 99.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 277,
    name: 'Cycling Glasses',
    price_per_quantity: 89.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 278,
    name: 'Tide Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 279,
    name: 'Safari Hat',
    price_per_quantity: 59.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 280,
    name: 'Insulated Jacket',
    price_per_quantity: 159.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 281,
    name: 'Peasant Blouse',
    price_per_quantity: 54.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 282,
    name: 'Capri Leggings',
    price_per_quantity: 44.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 283,
    name: 'Driving Shoes',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 284,
    name: 'Glacier Glasses',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 285,
    name: 'Barometer Watch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 286,
    name: "Tam O'Shanter",
    price_per_quantity: 44.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 287,
    name: 'Car Coat',
    price_per_quantity: 249.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 288,
    name: 'Boyfriend Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 289,
    name: 'Palazzo Pants',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 290,
    name: 'Oxford Brogues',
    price_per_quantity: 189.99,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 291,
    name: 'Fisherman Sunglasses',
    price_per_quantity: 99.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 292,
    name: 'Atomic Clock Watch',
    price_per_quantity: 899.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 293,
    name: 'Bush Hat',
    price_per_quantity: 49.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 294,
    name: 'Mackintosh Coat',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 295,
    name: 'Peplum Top',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 296,
    name: 'Riding Pants',
    price_per_quantity: 109.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 297,
    name: 'Ghillie Shoes',
    price_per_quantity: 129.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 298,
    name: 'Wraparound Glasses',
    price_per_quantity: 79.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 299,
    name: 'World Time Watch',
    price_per_quantity: 749.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 300,
    name: 'Tyrolean Hat',
    price_per_quantity: 74.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 301,
    name: 'Moisture-wicking Shirt',
    price_per_quantity: 42.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 302,
    name: 'Drawstring Pants',
    price_per_quantity: 54.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 303,
    name: 'Trail Running Shoes',
    price_per_quantity: 139.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 304,
    name: 'Floating Sunglasses',
    price_per_quantity: 109.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 305,
    name: 'Solar-powered Watch',
    price_per_quantity: 349.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 306,
    name: 'Newsboy Hat',
    price_per_quantity: 52.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 307,
    name: 'Wool Pea Coat',
    price_per_quantity: 259.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 308,
    name: 'Crew Neck Sweater',
    price_per_quantity: 64.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 309,
    name: 'Relaxed Fit Jeans',
    price_per_quantity: 84.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 310,
    name: 'Cross-training Shoes',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 311,
    name: 'Flip-up Sunglasses',
    price_per_quantity: 89.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 312,
    name: 'Perpetual Watch',
    price_per_quantity: 1599.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 313,
    name: 'Ascot Cap',
    price_per_quantity: 47.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 314,
    name: 'Reversible Jacket',
    price_per_quantity: 129.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 315,
    name: 'Muscle Tank',
    price_per_quantity: 22.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 316,
    name: 'Straight Leg Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 317,
    name: 'Water Shoes',
    price_per_quantity: 49.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 318,
    name: 'Folding Sunglasses',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 319,
    name: 'Eco-friendly Watch',
    price_per_quantity: 199.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 320,
    name: 'Wide-brim Hat',
    price_per_quantity: 69.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 321,
    name: 'Quilted Jacket',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 322,
    name: 'Performance Polo',
    price_per_quantity: 54.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 323,
    name: 'Elastic Waist Pants',
    price_per_quantity: 44.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 324,
    name: 'Minimalist Sneakers',
    price_per_quantity: 89.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 325,
    name: 'Bamboo Sunglasses',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 326,
    name: 'Skeleton Dial Watch',
    price_per_quantity: 449.99,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 327,
    name: 'Crusher Hat',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 328,
    name: 'Softshell Vest',
    price_per_quantity: 79.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 329,
    name: 'Tri-blend Tee',
    price_per_quantity: 28.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 330,
    name: 'Tech Pants',
    price_per_quantity: 89.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 331,
    name: 'Slip-resistant Shoes',
    price_per_quantity: 109.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 332,
    name: 'Wood Frame Sunglasses',
    price_per_quantity: 129.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 333,
    name: 'Smart Fitness Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 334,
    name: 'Fisherman Hat',
    price_per_quantity: 42.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 335,
    name: 'Technical Jacket',
    price_per_quantity: 199.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Yellow',
  },
  {
    id: 336,
    name: 'Burnout Tee',
    price_per_quantity: 32.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 337,
    name: 'Compression Pants',
    price_per_quantity: 64.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 338,
    name: 'Breathable Sneakers',
    price_per_quantity: 129.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 339,
    name: 'Titanium Sunglasses',
    price_per_quantity: 299.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 340,
    name: 'Analog-digital Watch',
    price_per_quantity: 179.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 341,
    name: 'Outback Hat',
    price_per_quantity: 79.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 342,
    name: 'Hooded Jacket',
    price_per_quantity: 119.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 343,
    name: 'Moisture-control Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Green',
  },
  {
    id: 344,
    name: 'Five-pocket Pants',
    price_per_quantity: 74.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 345,
    name: 'Zero-drop Shoes',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 346,
    name: 'Interchangeable Sunglasses',
    price_per_quantity: 159.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 347,
    name: 'Bluetooth Watch',
    price_per_quantity: 249.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 348,
    name: 'Ranger Hat',
    price_per_quantity: 59.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 349,
    name: 'Insulated Vest',
    price_per_quantity: 89.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 350,
    name: 'Ringer Tee',
    price_per_quantity: 26.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 351,
    name: 'Convertible Pants',
    price_per_quantity: 94.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 352,
    name: 'Lightweight Runners',
    price_per_quantity: 119.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 353,
    name: 'Anti-fog Sunglasses',
    price_per_quantity: 119.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 354,
    name: 'Kinetic Energy Watch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 355,
    name: 'Expedition Hat',
    price_per_quantity: 64.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 356,
    name: 'Packable Jacket',
    price_per_quantity: 109.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Red',
  },
  {
    id: 357,
    name: 'Quick-dry Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 358,
    name: 'Stretch Pants',
    price_per_quantity: 59.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 359,
    name: 'Barefoot Shoes',
    price_per_quantity: 99.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 360,
    name: 'Gradient Lens Sunglasses',
    price_per_quantity: 139.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 361,
    name: 'Heart Rate Watch',
    price_per_quantity: 189.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 362,
    name: 'Mesh Hat',
    price_per_quantity: 29.99,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 363,
    name: 'Hybrid Jacket',
    price_per_quantity: 159.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 364,
    name: 'Seamless Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 365,
    name: 'Travel Pants',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 366,
    name: 'Recovery Shoes',
    price_per_quantity: 89.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 367,
    name: 'Adjustable Sunglasses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 368,
    name: 'Temperature Watch',
    price_per_quantity: 279.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 369,
    name: 'Adventure Hat',
    price_per_quantity: 54.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 370,
    name: 'Storm Jacket',
    price_per_quantity: 229.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 371,
    name: 'Seamless Tank',
    price_per_quantity: 34.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 372,
    name: 'Performance Shorts',
    price_per_quantity: 49.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 373,
    name: 'Stability Shoes',
    price_per_quantity: 159.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 374,
    name: 'Mirrored Aviators',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Yellow',
  },
  {
    id: 375,
    name: 'Carbon Fiber Watch',
    price_per_quantity: 899.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 376,
    name: 'Packable Hat',
    price_per_quantity: 39.99,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 377,
    name: 'Alpine Jacket',
    price_per_quantity: 299.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 378,
    name: 'Anti-microbial Shirt',
    price_per_quantity: 52.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 379,
    name: 'Tactical Pants',
    price_per_quantity: 89.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 380,
    name: 'Approach Shoes',
    price_per_quantity: 139.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 381,
    name: 'Scratch-resistant Sunglasses',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 382,
    name: 'Atomic Time Watch',
    price_per_quantity: 549.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 383,
    name: 'Ventilated Hat',
    price_per_quantity: 47.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 384,
    name: 'Expedition Jacket',
    price_per_quantity: 379.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 385,
    name: 'Odor-resistant Shirt',
    price_per_quantity: 44.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 386,
    name: 'Ripstop Pants',
    price_per_quantity: 69.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 387,
    name: 'Climbing Shoes',
    price_per_quantity: 179.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 388,
    name: 'Prescription Sunglasses',
    price_per_quantity: 249.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 389,
    name: 'Multi-timezone Watch',
    price_per_quantity: 699.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 390,
    name: 'UV Protection Hat',
    price_per_quantity: 49.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 391,
    name: 'Three-season Jacket',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 392,
    name: 'Merino Wool Shirt',
    price_per_quantity: 89.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 393,
    name: 'Climbing Pants',
    price_per_quantity: 109.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 394,
    name: 'Approach Boots',
    price_per_quantity: 199.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 395,
    name: 'Glacier Sunglasses',
    price_per_quantity: 199.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 396,
    name: 'Expedition Watch',
    price_per_quantity: 799.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 397,
    name: 'Mountaineering Hat',
    price_per_quantity: 74.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 398,
    name: 'Hardshell Jacket',
    price_per_quantity: 349.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Yellow',
  },
  {
    id: 399,
    name: 'Base Layer Shirt',
    price_per_quantity: 59.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 400,
    name: 'Softshell Pants',
    price_per_quantity: 129.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 401,
    name: 'Mountaineering Boots',
    price_per_quantity: 349.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 402,
    name: 'High-altitude Sunglasses',
    price_per_quantity: 279.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 403,
    name: 'Altimeter Watch',
    price_per_quantity: 599.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 404,
    name: 'Summit Hat',
    price_per_quantity: 64.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 405,
    name: 'Expedition Parka',
    price_per_quantity: 499.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 406,
    name: 'Technical Base Layer',
    price_per_quantity: 69.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 407,
    name: 'Insulated Pants',
    price_per_quantity: 149.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 408,
    name: 'Ice Climbing Boots',
    price_per_quantity: 449.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 409,
    name: 'Mountaineering Goggles',
    price_per_quantity: 159.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 410,
    name: 'GPS Navigation Watch',
    price_per_quantity: 849.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 411,
    name: 'Cold Weather Hat',
    price_per_quantity: 89.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 412,
    name: 'Arctic Jacket',
    price_per_quantity: 599.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 413,
    name: 'Thermal Underwear Top',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 414,
    name: 'Snow Pants',
    price_per_quantity: 169.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 415,
    name: 'Winter Boots',
    price_per_quantity: 229.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 416,
    name: 'Snow Goggles',
    price_per_quantity: 129.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 417,
    name: 'Winter Sports Watch',
    price_per_quantity: 399.99,
    type: 'Watch',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 418,
    name: 'Ski Hat',
    price_per_quantity: 34.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 419,
    name: 'Ski Jacket',
    price_per_quantity: 299.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 420,
    name: 'Long Johns Top',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 421,
    name: 'Ski Pants',
    price_per_quantity: 199.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 422,
    name: 'Après-ski Boots',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 423,
    name: 'Ski Sunglasses',
    price_per_quantity: 179.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 424,
    name: 'Snow Sports Watch',
    price_per_quantity: 299.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 425,
    name: 'Snowboard Hat',
    price_per_quantity: 42.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 426,
    name: 'Snowboard Jacket',
    price_per_quantity: 279.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Yellow',
  },
  {
    id: 427,
    name: 'Wicking Base Layer',
    price_per_quantity: 54.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 428,
    name: 'Snowboard Pants',
    price_per_quantity: 189.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 429,
    name: 'Snow Boots',
    price_per_quantity: 179.99,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 430,
    name: 'Winter Sport Goggles',
    price_per_quantity: 149.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 431,
    name: 'Adventure Sports Watch',
    price_per_quantity: 459.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 432,
    name: 'Winter Adventure Hat',
    price_per_quantity: 59.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 433,
    name: 'All-weather Jacket',
    price_per_quantity: 249.99,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 434,
    name: 'Multi-sport Shirt',
    price_per_quantity: 64.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 435,
    name: 'All-terrain Pants',
    price_per_quantity: 119.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 436,
    name: 'All-terrain Boots',
    price_per_quantity: 219.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 437,
    name: 'All-weather Sunglasses',
    price_per_quantity: 169.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 438,
    name: 'Adventure Watch',
    price_per_quantity: 379.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 439,
    name: 'Exploration Hat',
    price_per_quantity: 69.99,
    type: 'Hat',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 440,
    name: 'Explorer Jacket',
    price_per_quantity: 329.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 441,
    name: 'Adventure Shirt',
    price_per_quantity: 74.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 442,
    name: 'Expedition Trousers',
    price_per_quantity: 139.99,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 443,
    name: 'Explorer Boots',
    price_per_quantity: 259.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 444,
    name: 'Explorer Sunglasses',
    price_per_quantity: 189.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 445,
    name: 'Explorer Watch',
    price_per_quantity: 649.99,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 446,
    name: 'Frontier Hat',
    price_per_quantity: 79.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 447,
    name: 'Frontier Jacket',
    price_per_quantity: 299.99,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 448,
    name: 'Frontier Shirt',
    price_per_quantity: 69.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 449,
    name: 'Frontier Pants',
    price_per_quantity: 129.99,
    type: 'Pants',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 450,
    name: 'Frontier Boots',
    price_per_quantity: 249.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 451,
    name: 'Summit Jacket',
    price_per_quantity: 189.99,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 452,
    name: 'Urban Slim Pants',
    price_per_quantity: 79.5,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 453,
    name: 'Vintage Leather Watch',
    price_per_quantity: 220.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 454,
    name: 'Classic White Shirt',
    price_per_quantity: 45.0,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 455,
    name: 'Aero Running Shoes',
    price_per_quantity: 130.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 456,
    name: 'Explorer Sunglasses',
    price_per_quantity: 89.5,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 457,
    name: 'Essential Casual Hat',
    price_per_quantity: 29.99,
    type: 'Hat',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 458,
    name: 'Frontline Cargo Pants',
    price_per_quantity: 69.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 459,
    name: 'Heritage Wool Jacket',
    price_per_quantity: 210.25,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 460,
    name: 'Midnight Sport Watch',
    price_per_quantity: 159.75,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 461,
    name: 'Nomad Hiking Shoes',
    price_per_quantity: 140.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 462,
    name: 'Solar Sunglasses',
    price_per_quantity: 99.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 463,
    name: 'Adventure Cap',
    price_per_quantity: 24.5,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Red',
  },
  {
    id: 464,
    name: 'Smart Casual Shirt',
    price_per_quantity: 55.25,
    type: 'Shirt',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 465,
    name: 'Classic Denim Pants',
    price_per_quantity: 85.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 466,
    name: 'Vintage Leather Jacket',
    price_per_quantity: 225.0,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 467,
    name: 'Precision Sport Watch',
    price_per_quantity: 180.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 468,
    name: 'Urban Street Shoes',
    price_per_quantity: 120.5,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 469,
    name: 'Classic Aviator Sunglasses',
    price_per_quantity: 95.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 470,
    name: 'Retro Hat',
    price_per_quantity: 27.0,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 471,
    name: 'Luxury Shirt Collection',
    price_per_quantity: 75.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 472,
    name: 'Slim Fit Pants',
    price_per_quantity: 88.5,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 473,
    name: 'Explorer Leather Jacket',
    price_per_quantity: 240.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 474,
    name: 'Classic Chrono Watch',
    price_per_quantity: 199.99,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 475,
    name: 'Trail Running Shoes',
    price_per_quantity: 135.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 476,
    name: 'Polarized Sunglasses',
    price_per_quantity: 105.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 477,
    name: 'Urban Cap',
    price_per_quantity: 22.5,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 478,
    name: 'Heritage Casual Shirt',
    price_per_quantity: 60.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 479,
    name: 'Modern Pants Line',
    price_per_quantity: 90.0,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 480,
    name: 'Nomad Leather Jacket',
    price_per_quantity: 215.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 481,
    name: 'Precision Watch Series',
    price_per_quantity: 185.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 482,
    name: 'Urban Sneakers',
    price_per_quantity: 125.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 483,
    name: 'Retro Sunglasses Design',
    price_per_quantity: 92.5,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 484,
    name: 'Classic Baseball Hat',
    price_per_quantity: 26.0,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Red',
  },
  {
    id: 485,
    name: 'Essential Shirt',
    price_per_quantity: 50.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 486,
    name: 'Slim Cargo Pants',
    price_per_quantity: 80.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 487,
    name: 'Heritage Leather Jacket',
    price_per_quantity: 230.0,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 488,
    name: 'Classic Sport Watch',
    price_per_quantity: 170.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 489,
    name: 'Trail Shoes',
    price_per_quantity: 140.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 490,
    name: 'Explorer Sunglasses Edition',
    price_per_quantity: 100.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 491,
    name: 'Casual Cap',
    price_per_quantity: 25.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 492,
    name: 'Modern Shirt Line',
    price_per_quantity: 65.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 493,
    name: 'Urban Pants Collection',
    price_per_quantity: 85.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 494,
    name: 'Nomad Jacket',
    price_per_quantity: 220.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 495,
    name: 'Precision Watch Model',
    price_per_quantity: 190.0,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 496,
    name: 'Urban Running Shoes',
    price_per_quantity: 130.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 497,
    name: 'Classic Sunglasses',
    price_per_quantity: 95.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 498,
    name: 'Retro Hat Edition',
    price_per_quantity: 28.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 499,
    name: 'Luxury Shirt Model',
    price_per_quantity: 75.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 500,
    name: 'Slim Pants Line',
    price_per_quantity: 88.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 501,
    name: 'Explorer Leather Jacket',
    price_per_quantity: 240.0,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 502,
    name: 'Classic Chrono Watch',
    price_per_quantity: 199.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 503,
    name: 'Trail Running Shoes',
    price_per_quantity: 135.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 504,
    name: 'Polarized Sunglasses',
    price_per_quantity: 105.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 505,
    name: 'Urban Cap',
    price_per_quantity: 22.5,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 506,
    name: 'Heritage Casual Shirt',
    price_per_quantity: 60.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 507,
    name: 'Modern Pants Line',
    price_per_quantity: 90.0,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 508,
    name: 'Nomad Leather Jacket',
    price_per_quantity: 215.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 509,
    name: 'Precision Watch Series',
    price_per_quantity: 185.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 510,
    name: 'Urban Sneakers',
    price_per_quantity: 125.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 511,
    name: 'Retro Sunglasses Design',
    price_per_quantity: 92.5,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 512,
    name: 'Classic Baseball Hat',
    price_per_quantity: 26.0,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Red',
  },
  {
    id: 513,
    name: 'Essential Shirt',
    price_per_quantity: 50.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 514,
    name: 'Slim Cargo Pants',
    price_per_quantity: 80.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 515,
    name: 'Heritage Leather Jacket',
    price_per_quantity: 230.0,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 516,
    name: 'Classic Sport Watch',
    price_per_quantity: 170.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 517,
    name: 'Trail Shoes',
    price_per_quantity: 140.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 518,
    name: 'Explorer Sunglasses Edition',
    price_per_quantity: 100.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 519,
    name: 'Casual Cap',
    price_per_quantity: 25.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 520,
    name: 'Modern Shirt Line',
    price_per_quantity: 65.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 521,
    name: 'Urban Pants Collection',
    price_per_quantity: 85.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 522,
    name: 'Nomad Jacket',
    price_per_quantity: 220.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 523,
    name: 'Precision Watch Model',
    price_per_quantity: 190.0,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 524,
    name: 'Urban Running Shoes',
    price_per_quantity: 130.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 525,
    name: 'Classic Sunglasses',
    price_per_quantity: 95.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 526,
    name: 'Retro Hat Edition',
    price_per_quantity: 28.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 527,
    name: 'Luxury Shirt Model',
    price_per_quantity: 75.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 528,
    name: 'Slim Pants Line',
    price_per_quantity: 88.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 529,
    name: 'Explorer Leather Jacket',
    price_per_quantity: 240.0,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 530,
    name: 'Classic Chrono Watch',
    price_per_quantity: 199.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 531,
    name: 'Trail Running Shoes',
    price_per_quantity: 135.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 532,
    name: 'Polarized Sunglasses',
    price_per_quantity: 105.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 533,
    name: 'Urban Cap',
    price_per_quantity: 22.5,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 534,
    name: 'Heritage Casual Shirt',
    price_per_quantity: 60.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 535,
    name: 'Modern Pants Line',
    price_per_quantity: 90.0,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 536,
    name: 'Nomad Leather Jacket',
    price_per_quantity: 215.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 537,
    name: 'Precision Watch Series',
    price_per_quantity: 185.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 538,
    name: 'Urban Sneakers',
    price_per_quantity: 125.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 539,
    name: 'Retro Sunglasses Design',
    price_per_quantity: 92.5,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 540,
    name: 'Classic Baseball Hat',
    price_per_quantity: 26.0,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Red',
  },
  {
    id: 541,
    name: 'Essential Shirt',
    price_per_quantity: 50.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 542,
    name: 'Slim Cargo Pants',
    price_per_quantity: 80.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 543,
    name: 'Heritage Leather Jacket',
    price_per_quantity: 230.0,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Brown',
  },
  {
    id: 544,
    name: 'Classic Sport Watch',
    price_per_quantity: 170.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 545,
    name: 'Trail Shoes',
    price_per_quantity: 140.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 546,
    name: 'Explorer Sunglasses Edition',
    price_per_quantity: 100.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 547,
    name: 'Casual Cap',
    price_per_quantity: 25.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 548,
    name: 'Modern Shirt Line',
    price_per_quantity: 65.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 549,
    name: 'Urban Pants Collection',
    price_per_quantity: 85.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 550,
    name: 'Nomad Jacket',
    price_per_quantity: 220.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 551,
    name: 'Summit Hiking Shoes',
    price_per_quantity: 149.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 552,
    name: 'Urban Denim Jacket',
    price_per_quantity: 199.5,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 553,
    name: 'Classic Polo Shirt',
    price_per_quantity: 49.99,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 554,
    name: 'Explorer Cargo Pants',
    price_per_quantity: 89.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 555,
    name: 'Heritage Aviator Sunglasses',
    price_per_quantity: 120.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 556,
    name: 'Minimalist Leather Watch',
    price_per_quantity: 250.0,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 557,
    name: 'Retro Baseball Hat',
    price_per_quantity: 35.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 558,
    name: 'Essential V-Neck Shirt',
    price_per_quantity: 40.0,
    type: 'Shirt',
    status: 'Not in stock',
    color: 'Gray',
  },
  {
    id: 559,
    name: 'Slim Fit Chinos',
    price_per_quantity: 75.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 560,
    name: 'Expedition Parka Jacket',
    price_per_quantity: 280.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },

  {
    id: 561,
    name: 'Trail Runner Shoes',
    price_per_quantity: 135.0,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'Yellow',
  },
  {
    id: 562,
    name: 'Polarized Explorer Sunglasses',
    price_per_quantity: 99.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 563,
    name: 'Chronograph Steel Watch',
    price_per_quantity: 300.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 564,
    name: 'Everyday Cotton Hat',
    price_per_quantity: 20.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 565,
    name: 'Premium Linen Shirt',
    price_per_quantity: 65.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 566,
    name: 'Cargo Utility Pants',
    price_per_quantity: 85.0,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Green',
  },
  {
    id: 567,
    name: 'Urban Biker Jacket',
    price_per_quantity: 210.0,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 568,
    name: 'Heritage Leather Shoes',
    price_per_quantity: 175.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 569,
    name: 'Modern Aviator Sunglasses',
    price_per_quantity: 110.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 570,
    name: 'Digital Sport Watch',
    price_per_quantity: 145.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },

  {
    id: 571,
    name: 'Classic Trucker Hat',
    price_per_quantity: 28.0,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 572,
    name: 'Office Formal Shirt',
    price_per_quantity: 55.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'Blue',
  },
  {
    id: 573,
    name: 'Relaxed Fit Pants',
    price_per_quantity: 70.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 574,
    name: 'Retro Windbreaker Jacket',
    price_per_quantity: 160.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 575,
    name: 'Performance Running Shoes',
    price_per_quantity: 140.0,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Red',
  },
  {
    id: 576,
    name: 'Luxury Polarized Sunglasses',
    price_per_quantity: 135.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 577,
    name: 'Titanium Luxury Watch',
    price_per_quantity: 450.0,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Gray',
  },
  {
    id: 578,
    name: 'Beach Straw Hat',
    price_per_quantity: 18.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 579,
    name: 'Casual Button Shirt',
    price_per_quantity: 48.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 580,
    name: 'Slim Denim Pants',
    price_per_quantity: 95.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },

  {
    id: 581,
    name: 'Summit Wind Jacket',
    price_per_quantity: 155.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 582,
    name: 'Heritage Oxford Shirt',
    price_per_quantity: 62.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 583,
    name: 'All-Terrain Boots',
    price_per_quantity: 160.5,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 584,
    name: 'Classic Chino Pants',
    price_per_quantity: 78.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 585,
    name: 'Sculpt Sunglasses',
    price_per_quantity: 88.0,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 586,
    name: 'Navigator Field Jacket',
    price_per_quantity: 230.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 587,
    name: 'Metro Casual Hat',
    price_per_quantity: 24.99,
    type: 'Hat',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 588,
    name: 'Precision Sport Chrono',
    price_per_quantity: 210.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 589,
    name: 'Heritage Brogue Shoes',
    price_per_quantity: 180.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 590,
    name: 'Lightweight Travel Pants',
    price_per_quantity: 72.5,
    type: 'Pants',
    status: 'In stock',
    color: 'Gray',
  },

  {
    id: 591,
    name: 'Urban Slim Shirt',
    price_per_quantity: 52.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 592,
    name: 'Explorer Snow Jacket',
    price_per_quantity: 320.0,
    type: 'Jacket',
    status: 'Not in stock',
    color: 'White',
  },
  {
    id: 593,
    name: 'Street Runner Shoes',
    price_per_quantity: 120.0,
    type: 'Shoes',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 594,
    name: 'Coastal Sunglasses',
    price_per_quantity: 79.99,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 595,
    name: 'Heritage Linen Pants',
    price_per_quantity: 82.0,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 596,
    name: 'Essential Beanie Hat',
    price_per_quantity: 19.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 597,
    name: 'Classic Dress Watch',
    price_per_quantity: 275.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 598,
    name: 'Metro Leather Sneakers',
    price_per_quantity: 145.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 599,
    name: 'Timeless Aviator Sunglasses',
    price_per_quantity: 115.0,
    type: 'Sunglasses',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 600,
    name: 'Nomad Trail Jacket',
    price_per_quantity: 205.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },

  {
    id: 601,
    name: 'Classic Henley Shirt',
    price_per_quantity: 44.5,
    type: 'Shirt',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 602,
    name: 'Performance Chino Pants',
    price_per_quantity: 79.99,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 603,
    name: 'Heritage Chelsea Boots',
    price_per_quantity: 185.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 604,
    name: 'Reflect Sunglasses',
    price_per_quantity: 98.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 605,
    name: 'Compact Field Watch',
    price_per_quantity: 132.5,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Black',
  },
  {
    id: 606,
    name: 'Essential Baseball Hat',
    price_per_quantity: 21.0,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 607,
    name: 'Urban Cargo Pants',
    price_per_quantity: 86.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
  {
    id: 608,
    name: 'Cozy Fleece Jacket',
    price_per_quantity: 120.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 609,
    name: 'Slim Oxford Shirt',
    price_per_quantity: 58.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 610,
    name: 'Trail Grip Shoes',
    price_per_quantity: 142.0,
    type: 'Shoes',
    status: 'Not in stock',
    color: 'Black',
  },

  {
    id: 611,
    name: 'Navigator Sunglasses',
    price_per_quantity: 104.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 612,
    name: 'Minimalist Canvas Hat',
    price_per_quantity: 23.5,
    type: 'Hat',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 613,
    name: 'Executive Dress Shirt',
    price_per_quantity: 85.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 614,
    name: 'Classic Straight Pants',
    price_per_quantity: 77.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 615,
    name: 'Heritage Bomber Jacket',
    price_per_quantity: 195.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 616,
    name: 'Urban Trek Shoes',
    price_per_quantity: 150.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 617,
    name: 'Polarized Sport Sunglasses',
    price_per_quantity: 112.0,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 618,
    name: 'Chrono Field Watch',
    price_per_quantity: 210.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 619,
    name: 'Retro Panama Hat',
    price_per_quantity: 29.0,
    type: 'Hat',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 620,
    name: 'Everyday Linen Shirt',
    price_per_quantity: 54.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'Blue',
  },

  {
    id: 621,
    name: 'Street Cargo Pants',
    price_per_quantity: 82.0,
    type: 'Pants',
    status: 'On the way to stock',
    color: 'Green',
  },
  {
    id: 622,
    name: 'Explorer Rain Jacket',
    price_per_quantity: 150.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 623,
    name: 'Minimalist Slip-Ons',
    price_per_quantity: 95.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 624,
    name: 'Classic Round Sunglasses',
    price_per_quantity: 89.5,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 625,
    name: 'Precision Pilot Watch',
    price_per_quantity: 260.0,
    type: 'Watch',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 626,
    name: 'Vintage Fisherman Hat',
    price_per_quantity: 17.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 627,
    name: 'Casual Stripe Shirt',
    price_per_quantity: 46.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 628,
    name: 'Relaxed Jogger Pants',
    price_per_quantity: 68.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 629,
    name: 'Heritage Riding Jacket',
    price_per_quantity: 245.0,
    type: 'Jacket',
    status: 'On the way to stock',
    color: 'Brown',
  },
  {
    id: 630,
    name: 'Urban Classic Watch',
    price_per_quantity: 175.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Blue',
  },

  {
    id: 631,
    name: 'Mountain Trail Shoes',
    price_per_quantity: 155.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'Brown',
  },
  {
    id: 632,
    name: 'Aero Sport Shirt',
    price_per_quantity: 39.99,
    type: 'Shirt',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 633,
    name: 'Explorer Denim Pants',
    price_per_quantity: 92.0,
    type: 'Pants',
    status: 'Not in stock',
    color: 'Blue',
  },
  {
    id: 634,
    name: 'Classic Wayfarer Sunglasses',
    price_per_quantity: 99.0,
    type: 'Sunglasses',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 635,
    name: 'Precision Slim Watch',
    price_per_quantity: 198.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 636,
    name: 'Canvas Snapback Hat',
    price_per_quantity: 24.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Red',
  },
  {
    id: 637,
    name: 'Essential Polo Shirt',
    price_per_quantity: 47.0,
    type: 'Shirt',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 638,
    name: 'Tech Performance Pants',
    price_per_quantity: 99.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 639,
    name: 'Nomad Windbreaker Jacket',
    price_per_quantity: 165.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 640,
    name: 'Classic Timeless Watch',
    price_per_quantity: 320.0,
    type: 'Watch',
    status: 'On the way to stock',
    color: 'Brown',
  },

  {
    id: 641,
    name: 'Street Flex Shoes',
    price_per_quantity: 128.0,
    type: 'Shoes',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 642,
    name: 'Lightweight Summer Shirt',
    price_per_quantity: 34.5,
    type: 'Shirt',
    status: 'In stock',
    color: 'Yellow',
  },
  {
    id: 643,
    name: 'Chill Linen Pants',
    price_per_quantity: 71.0,
    type: 'Pants',
    status: 'In stock',
    color: 'White',
  },
  {
    id: 644,
    name: 'Retro Pilot Sunglasses',
    price_per_quantity: 108.0,
    type: 'Sunglasses',
    status: 'Not in stock',
    color: 'Black',
  },
  {
    id: 645,
    name: 'Heritage Dress Watch',
    price_per_quantity: 285.0,
    type: 'Watch',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 646,
    name: 'Foldable Travel Hat',
    price_per_quantity: 20.0,
    type: 'Hat',
    status: 'In stock',
    color: 'Blue',
  },
  {
    id: 647,
    name: 'Urban Zip Jacket',
    price_per_quantity: 142.0,
    type: 'Jacket',
    status: 'In stock',
    color: 'Black',
  },
  {
    id: 648,
    name: 'Classic Plimsoll Shoes',
    price_per_quantity: 99.99,
    type: 'Shoes',
    status: 'In stock',
    color: 'Gray',
  },
  {
    id: 649,
    name: 'Everyday Oxford Shirt',
    price_per_quantity: 59.0,
    type: 'Shirt',
    status: 'On the way to stock',
    color: 'White',
  },
  {
    id: 650,
    name: 'Nomad Travel Pants',
    price_per_quantity: 88.0,
    type: 'Pants',
    status: 'In stock',
    color: 'Green',
  },
];
